{"name": "test_mark_function_by_process_tag_working_exception", "status": "broken", "statusDetails": {"message": "Exception: Autogenerated Exception.", "trace": "self = <tests.test_report.TestClass object at 0x7fc2ce66b0f0>\n\n    @pytest.mark.test_process_marks(\"Working\")\n    def test_mark_function_by_process_tag_working_exception(self):\n>       raise Exception(\"Autogenerated Exception.\")\nE       Exception: Autogenerated Exception.\n\ntests/test_report.py:20: Exception"}, "attachments": [{"name": "log", "source": "b407baf0-d648-4732-9fe3-d9a16ad63871-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "97ae9e5b-ad57-426f-8f29-b9a91f3dac44-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "18984bcd-4251-431e-8d19-ee25f5d5354e-attachment.txt", "type": "text/plain"}], "start": 1554841904736, "stop": 1554841904736, "uuid": "f42f70ad-4dd4-455b-85e3-d0e841eef942", "historyId": "30ba1d34e3af98868088428607c07b34", "fullName": "tests.test_report.TestClass#test_mark_function_by_process_tag_working_exception", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_report"}, {"name": "subSuite", "value": "TestClass"}, {"name": "host", "value": "travis-job-6d6db9cc-16b5-4dbc-9e05-ca127110bbfc"}, {"name": "thread", "value": "3718-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_report"}]}