{"name": "test_mark_function_by_process_tag_working_that_pass", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '/Users/cibanez/development/pytest_example/imgs/python.png'", "trace": "item = <Function test_mark_function_by_process_tag_working_that_pass>\n\n    def pytest_runtest_setup(item: Item):\n        # called before pytest_runtest_call(item).\n    \n        def get_my_custom_marks(item: Item):\n            \"\"\":return list with the marks of the test that are included in marks_to_run or marks_to_skip \"\"\"\n            marks = []\n            for mark in item.own_markers:\n                if mark.name not in MARKERS_PROCESS_TAG:\n                    marks.append(mark.name)\n            return marks\n    \n        def get_test_item(item: Item):\n            test_dict = {}\n            node_id = item.nodeid\n            process_tag = []\n            is_process_tag = False\n    \n            for marker in item.iter_markers(name=\"test_process_marks\"):\n                process_tag.append(marker.args[0])\n                is_process_tag = True\n    \n            if not is_process_tag:\n                is_process_tag = False\n    \n            other_marks = get_my_custom_marks(item)\n            test_dict.update({node_id:\n                                  {\"test_process_marks\": process_tag,\n                                   \"is_process_tag\": is_process_tag,\n                                   \"test_marks\": other_marks,\n                                   \"test_name\": item.name}})\n    \n            return test_dict\n    \n        test_item = get_test_item(item=item)\n        item_id = list(test_item.keys())[0]\n    \n        tests_list.append(item_id)\n    \n        process_test_marks(test_item=test_item, item_id=item_id)\n    \n    \n        import allure\n        screenshot_name = \"Python image\"\n        screenshot_path = \"/Users/cibanez/development/pytest_example/imgs/python.png\"\n        allure.attach.file(source=screenshot_path,\n>                              name=screenshot_name, attachment_type=allure.attachment_type.PNG)\n\nconftest.py:139: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n../../../virtualenv/python3.6.3/lib/python3.6/site-packages/allure_commons/_allure.py:151: in file\n    plugin_manager.hook.attach_file(source=source, name=name, attachment_type=attachment_type, extension=extension)\n../../../virtualenv/python3.6.3/lib/python3.6/site-packages/allure_pytest/listener.py:211: in attach_file\n    self.allure_logger.attach_file(uuid4(), source, name=name, attachment_type=attachment_type, extension=extension)\n../../../virtualenv/python3.6.3/lib/python3.6/site-packages/allure_commons/reporter.py:113: in attach_file\n    plugin_manager.hook.report_attached_file(source=source, file_name=file_name)\n../../../virtualenv/python3.6.3/lib/python3.6/site-packages/allure_commons/logger.py:48: in report_attached_file\n    shutil.copy2(source, destination)\n../../../virtualenv/python3.6.3/lib/python3.6/shutil.py:257: in copy2\n    copyfile(src, dst, follow_symlinks=follow_symlinks)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nsrc = '/Users/cibanez/development/pytest_example/imgs/python.png'\ndst = '/home/travis/build/cariel27/pytest_example/allure_results/9a6c7682-2802-4173-ac01-3a02de988a97-attachment.png'\n\n    def copyfile(src, dst, *, follow_symlinks=True):\n        \"\"\"Copy data from src to dst.\n    \n        If follow_symlinks is not set and src is a symbolic link, a new\n        symlink will be created instead of copying the file it points to.\n    \n        \"\"\"\n        if _samefile(src, dst):\n            raise SameFileError(\"{!r} and {!r} are the same file\".format(src, dst))\n    \n        for fn in [src, dst]:\n            try:\n                st = os.stat(fn)\n            except OSError:\n                # File most likely does not exist\n                pass\n            else:\n                # XXX What about other special files? (sockets, devices...)\n                if stat.S_ISFIFO(st.st_mode):\n                    raise SpecialFileError(\"`%s` is a named pipe\" % fn)\n    \n        if not follow_symlinks and os.path.islink(src):\n            os.symlink(os.readlink(src), dst)\n        else:\n>           with open(src, 'rb') as fsrc:\nE           FileNotFoundError: [Errno 2] No such file or directory: '/Users/cibanez/development/pytest_example/imgs/python.png'\n\n../../../virtualenv/python3.6.3/lib/python3.6/shutil.py:120: FileNotFoundError"}, "attachments": [{"name": "Python image", "source": "9a6c7682-2802-4173-ac01-3a02de988a97-attachment.png", "type": "image/png"}, {"name": "log", "source": "7ad2f2ca-e94c-46c6-907d-eef4c63c611a-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "9b65ea32-b1cb-4a04-b8cb-1228d99eab3a-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "5acbefbd-2641-4cf5-8bef-883c12f6cd6a-attachment.txt", "type": "text/plain"}], "start": 1554741505560, "stop": 1554741505560, "uuid": "9674a8cf-e551-4e85-a1f0-91cd97d388a2", "historyId": "9743c5317ff1cfde22979972a75eb498", "fullName": "tests.test_report.TestClass#test_mark_function_by_process_tag_working_that_pass", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_report"}, {"name": "subSuite", "value": "TestClass"}, {"name": "host", "value": "travis-job-850ce131-4537-4f1c-8088-a57a5f2fcfff"}, {"name": "thread", "value": "3668-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_report"}]}